### ISSUE TITLE
frigate.events is not of a type(s) object

### ISSUE THREAD

**Issue by stephack** [jakowenko/double-take-hassio-addons#17]
I had this working a few months ago but stopped my testing because life got busy. I recently started up my docker containers including frigate/deepstack/doubletake but I'm not getting this "validation" error in my logs and in the webUI.

_frigate.events is not of a type(s) object_

I even recreated all the containers on a new server and get green lights on mqtt, frigate and deepstack but Doubltake has a yellow light in the UI. Any advice would be appreciated.

here's my yaml:

```
mqtt:
  host: 192.168.1.5
  username: !secret mqtt_user
  password: !secret mqtt_pass

frigate:
  url: http://192.168.1.5:5000
  events:
  attempts:
    latest: 0
    mqtt: true

detectors:
  deepstack:
    url: http://192.168.1.5:5001
   
detect:
  match:
    # minimum confidence needed to consider a result a match
    confidence: 80
    # minimum area in pixels to consider a result a match
    min_area: 2000

  unknown:
    # minimum confidence needed before classifying a name as unknown
    confidence: 40
    # minimum area in pixels to keep an unknown result
    min_area: 1999
```
