### ISSUE TITLE
Double Take can't connect to deep stack

### ISSUE THREAD

**Issue by jumping2000** [jakowenko/double-take-hassio-addons#2]
Double take addon can't connect to Deep Stack addon, maybe it's related to: 
https://community.home-assistant.io/t/facial-recognition-room-presence-using-double-take-frigate/290943/342

My double take conf:

```
mqtt:
  host: 192.168.1.101
  user: **
  password: **
    
frigate:
  url: http://192.168.1.101:5000
    
detectors:
  deepstack:
    url: http://192.168.1.101:5002
    timeout: 30
```

**Comment by jakowenko** [comment]
Hey @jumping2000, have you verified that `http://192.168.1.101:5002` shows the DeepStack homepage?

When you click on `DeepStack` in on your Double Take config page, what does the output show?

**Comment by jumping2000** [comment]
> 
> 
> Hey @jumping2000, have you verified that `http://192.168.1.101:5002` shows the DeepStack homepage?
> 
> When you click on `DeepStack` in on your Double Take config page, what does the output show?

Hi, 
2 days ago I deleted the deepstack addon and,  like many users, I switched to "deepstack-beta-cpu-X5" container, so now I can use Double Take with DeepStack and Frigate, but I don't like this solution, I will try Compreface solution.

Bye

**Comment by felipecrs** [comment]
BTW:

![image](https://user-images.githubusercontent.com/29582865/146384965-88f74cdd-4afb-4cf2-94fb-e2ae800051d3.png)

When I hover the mouse over DeepStack it says that it timed out.

**Comment by felipecrs** [comment]
And this is what the DeepStack logs says:

![image](https://user-images.githubusercontent.com/29582865/146386240-7acd1ff8-8226-4e37-87ae-b72685828492.png)

Also, switching to DeepStack CPU does not solve the issue for me.

This is my configuration:

```yaml
mqtt:
  host: core-mosquitto
  username: mqtt
  password: [hidden]

frigate:
  url: http://ccab4aaf-frigate:5000
  cameras:
    - video_porteiro_do_terreiro

detectors:
  deepstack:
    url: http://c7657554-deepstack:5000
```

![image](https://user-images.githubusercontent.com/29582865/146386581-e71951bb-98e8-4fe4-b740-b765a2ae57bc.png)

Increasing timeout does not help either:

![image](https://user-images.githubusercontent.com/29582865/146388416-72e98adc-2807-464e-aa01-c5620580000b.png)
