### ISSUE TITLE
Double take addon keeps stopping without error

### ISSUE THREAD

**Issue by dragonsoul84** [jakowenko/double-take-hassio-addons#22]
I have the Frigate Addon installed and working. I have the Deepstack CPU Addon installed. I have MQTT configured and working with other devices. I set the initial configuration for Double Take and when I start the Double Take Addon and go to the config tab I can see the green dots next to Double Take, MQTT, Frigate, and Deepstack. The log shows:

info: Double Take v1.13.1-8e2728d
info: MQTT: connected
info: MQTT: subscribed to frigate/events, frigate/+/person/snapshot

Then the Double Take dot on the config page turns red and the addon stops. No other info appears in log.

Edit: Adding info from UI log

23-02-03 20:21:05 info: Double Take v1.13.1-8e2728d
23-02-03 20:21:06 info: MQTT: connected
23-02-03 20:21:06 info: MQTT: subscribed to frigate/events, frigate/+/person/snapshot
23-02-03 20:21:28 info: Double Take v1.13.1-8e2728d
23-02-03 20:21:29 info: MQTT: connected
23-02-03 20:21:29 info: MQTT: subscribed to frigate/events, frigate/+/person/snapshot
23-02-03 20:21:49 info: Double Take v1.13.1-8e2728d
23-02-03 20:21:50 info: MQTT: connected
23-02-03 20:21:50 info: MQTT: subscribed to frigate/events, frigate/+/person/snapshot

Edit: Add config.yml

```
# MQTT Settings
mqtt:
  host: [homeassistant_ip_address]
  user: [mqtt_user_name]
  password: [mqtt_password]

# detector settings (default: shown below)
detectors:
  deepstack:
    url: http://[homeassistant_ip_address]:5001
    #key:
    # number of seconds before the request times out and is aborted
    timeout: 15
    # require opencv to find a face before processing with detector
    opencv_face_required: false
    # only process images from specific cameras, if omitted then all cameras will be processed
    # cameras:
    #   - front-door
    #   - garage
    
# Frigate Settings  
frigate:
  url: http://[homeassistant_ip_address]:5000
```
