### ISSUE TITLE
Compreface configuration in double take

### ISSUE THREAD

**Issue by thundergreen** [jakowenko/double-take-hassio-addons#6]
Hello I wanted to add several detector in double take but I am not sure how to add the api key in the double take config:

my double-take config looks like this

```
# Double Take
detectors:
  deepstack:
    url: http://192.168.1.41:5001
    timeout: 30
  compreface:
    url: http://192.168.1.41:8000
    api_key: 5a06f69b-8cce-420a-8294-1fb1d9f646e3
```
